# why do I make lists I can never maintain? this is super dumb
ARTISTS = {
    "Aaron Miller": "aarondraws",
    "Adam Paquette": "AdamPaquette",
    "Adam Rex": "MrAdamRex",
    "Alayna Danner": "windrune",
    "Alex Brock": "Slave_Eye",
    "Alex Konstad": "AlexKonstad",
    "Alex Stone": "AlexStoneArt",
    "Alexander Forssberg": "alexsonArt",
    "Alix Branwyn": "AlixBranwyn",
    "Allen Douglas": "adouglasstudio",
    "Allen Williams ➡️ IJustDraw (i_justdraw)": "ijustdraw",
    "Andrea Radeck": "ALRadeck",
    "Anna Steinbauer": "depingo",
    "Anson Maddocks": "AnsonMaddocks1",
    "Anthony Francisco": "Art_AF_",
    "Anthony Waters": "TheHairyCanary",
    "Antonio J. Manzanedo": "AJManzanedo",
    "Artur Treffner": "arturtreffner",
    "Bastien Grivet": "Grivetart",
    "Bastien L.Deharme": "deharme",
    "Ben Thompson": "BenThompsonArt",
    "Billy Christian": "bill_creative",
    "Brian Valeza": "tots_valeza",
    "Bram Sels": "bram_sels",
    "Brandi Milne": "brandimilne",
    "BROM": "GeraldBrom",
    "bumskee": "min_yum",
    "Campbell White": "moosebaby9000",
    "Carly💀Janine🎨Mazur": "CarlyLady",
    "CarmenSinek_Final_SuperFinal3.psd": "CarmenSinek",
    "Caroline Gariba": "carolinegariba",
    "Charles Urbach": "Artist_C_Urbach",
    "Chris Rahn": "ChrisRahnArt",
    "Chris Rallis": "ChrisRallis_Art",
    "Christine Choi": "christinechoi_",
    "Christopheles": "chrisseamanart",
    "Christopher Burdett": "ChrisBurdett",
    "christopher moeller": "cmoeller1",
    "Christopher Rush": "cRush_Art",
    "Cristi Balanescu": "cristi_426",
    "Chuck Lukacs he/him": "LightPusher",
    "Cornelius Brudi": "CorneliusBrudi",
    "Cynthia Sheppard": "SheppardArts",
    "Daisuke Izuka(okome)": "okome_di",
    "Dan Scott": "danscottart",
    "Daniel Warren Johnson": "danielwarrenart",
    "Darek Zabrocki": "DarekZabrocki",
    "Dave Greco": "DaveGrecoArt",
    "Dave Kendall": "DaveRustybaby",
    "David Rapoza": "DaveRapoza",
    "DaveDorman": "DaveDorman",
    "David Palumbo": "dave_palumbo",
    "david sladek": "dsladek1",
    "Denman": "DenmanRooke",
    "dermot power": "dermotpower",
    "Dimitar Marinski": "DimitarMarinski",
    "Dmitry Burmak": "DevBurmak",
    "DonatoArts": "DonatoArts",
    "Dopaprime": "dopaprime",
    "Drew Baker": "DrewBaker",
    "E. M. Gist": "E_M_Gist",
    "Emrah Elmasli": "emrahelmasli",
    "Eric Deschamps": "deschampsart",
    "Ernanda Souza": "ernanda91",
    "Evan Shipard": "_ev",
    "Even Mehl Amundsen @ Patreon": "EvenMAmundsen",
    "Eytan Zana": "EytanZana",
    "Filip Burburan": "filipburburan",
    "Florian deGesincourt": "DegesArt",
    "Fred Fields": "fredfieldsart",
    "G.River@Skeb開通してみました": "GR_River",
    "GlowingRaptor Studio": "glowingraptor",
    "Greg Hildebrandt": "HildebrandtGreg",
    "Greg Opalinski": "GregOpalinski",
    "Heather Hudson": "CandlemonkeyH",
    "Howard Lyon": "howardlyonart",
    "Ilse Gort": "CaraidArt",
    "Jake Murray Studio Ltd": "studio_murray",
    "James Paick": "JamesPaick",
    "JamesRymanArt": "RymanArt",
    "Jared Blando": "TheRedEpic",
    "jarel threat": "jarelthreat",
    "Jason Chan": "JasonChanArt",
    "Jason Engle": "J_A_E1",
    "Jason A. Engle": "J_A_E1",
    "Jason Felix": "Art_JasonFelix",
    "Jason Kang": "ArtofJasonKang",
    "Jason Rainville": "rhineville",
    "Jasper Sandner": "JasperSandner",
    "Jeff Laubenstein": "IllustratorJeff",
    "Jeff Miracola": "JeffMiracola",
    "Jen Bartel": "heyjenbartel",
    "Jenn Ravenna Tran": "JennRavenna",
    "Jeremy Wilson": "JeremyWilsonArt",
    "Jesper Myrfors": "JesperMyrfors",
    "Jim Nelson": "MothmanJim",
    "Jim Pavelec": "jim_pavelec",
    "Joe Slucher": "JoeSlucher",
    "Johannes Voss": "algenpfleger",
    "John Avon Art": "JohnAvonArt",
    "John Avon": "realJohnAvon",
    "John Zeleznik": "ZeleznikArt",
    "Jonas De Ro": "JonasDeRo",
    "Joseph Meehan": "JosephMeehanArt",
    "Josh Nelson": "Burning_Inquiry",
    "Joshua Meehan": "joshmeehanart",
    "Josu Hernaiz": "Josuoh",
    "Justyna Gil": "gilyoona",
    "Karla Ortiz": "kortizart",
    "Karlkopinski": "Karlkop",
    "Kekai Kotaki": "KekaiKotaki",
    "Kieran Yanner": "kieranyanner",
    "kilart (Choe, Heonhwa)": "kilart74",
    "Kim Sokol": "kimsokol",
    "Kimonas": "ArtOfKimonas",
    "Kirsten Zirngibl": "KirstenZirngibl",
    "lack@画集第3弾発売中": "lalalalack",
    "Lake Hurwitz": "lake_demonui",
    "Larry MacDougall 🇨🇦": "larrymacdougall",
    "Leesha Hannigan": "LeeshaHannigan",
    "Lena": "LenaSketchin",
    "Lie Setiawan": "ls_setiawan",
    "Lindsey Look": "LindseyLook",
    "Lius Lasahido": "lasahidoart",
    "Liz Danforth": "LizDanforth",
    "Lucas Graciano": "LucasJGraciano",
    "Magali Villeneuve": "Cathaoir1",
    "Margaret Organ-Kean": "Organ_Kean",
    "Mark Behm": "mark_behm",
    "Mark Winters": "MarkWintersArt",
    "Mark Zug": "markzug",
    "Marta Nael": "MartaNael",
    "Martina Fačková": "MFackova",
    "Matt Dixon": "MattDixonArt",
    "Matt Gaser": "MattGaser",
    "Matthew D.  Wilson": "MattWilsonPrime",
    "McLean Kendree": "mcleankendree",
    "Micah Epstein": "micahepsteinart",
    "Michael Whelan": "whelanmichael",
    "Mike Burns": "MikeBurnsAlive",
    "Mike Daarken Lim": "DaarkenArt",
    "Mike Uziel": "MikeUziel",
    "Mila Pesic": "milapesic8",
    "Milivoj Ćeran": "ArtMceran",
    "Mitchell Malloy": "mmalloyart",
    "Muhammad Firdaus": "freakyfir",
    "Naomi Baker": "Naomiful",
    "Nicholas Gregory": "daydream_cosmic",
    "nightmare weaver": "izzymedrano",
    "Nils Hamm": "nilshamm_art",
    "Noah Bradley": "noahbradley",
    "Ovidio Cartagena": "ovidiocartagena",
    "Paul Canavan": "abigbat",
    "Pauline Voss": "skadivore",
    "Pete Venters": "PeteVenters",
    "Peter Mohrbacher": "bugmeyer",
    "Philip Straub": "philstraub",
    "Piotr Dura": "piotrdura",
    "R. Kane Ferguson": "RKaneFerguson",
    "Ralph Horsley": "RalphHorsley",
    "Randy Gallegos": "gallegosart",
    "Randy Vargas": "VargasNi",
    "Richard Thomas": "rich_thomas_op",
    "Richard Whitters": "WhittersRichard",
    "rk post": "postrk",
    "Rob Alexander": "R_Alexander_Art",
    "Robbie Trevino": "RobbieSTrevino",
    "romiy": "akra105",
    "Ryan Alexander Lee": "ryanleeart",
    "Ryan Pancoast": "rpancoast_art",
    "Ryan Yee": "Artofryanyee",
    "Ryota-H": "Ryota_H",
    "Sam Burley": "SamBurleyArt",
    "Sara Winters": "SaraWintersArt",
    "Scott M Fischer": "Scott_M_Fischer",
    "Sean Andrew Murray": "SeanMurray_Art",
    "Seb McKinnon": "SebMcKinnon",
    "Shreya Shetty": "shreyashettyart",
    "Sidharth Chaturvedi": "schaturvedi",
    "Stanton Feng": "StantonFeng",
    "Stephan Martiniere": "smartiniere",
    "Steve Argyle": "Steve_Argyle",
    "Sue Ellen Brown": "ZooLNart",
    "Suzanne Helmigh - Arttips🎨": "SHelmigh",
    "Svetlin Velinov": "velinovart",
    "Sławomir Maniak": "maniakart",
    "Terese Nielsen": "tnielsenart",
    "Thomas M. Baxa": "BaxaArt",
    "Thomas Zenteno": "ThomasZenteno",
    "Titus 'HODL' Lunter": "TitusLunter",
    "Todd Lockwood": "ToddLockwoodArt",
    "Toma Feizo Gas": "eizOga",
    "Tomas Duchek": "dusin3000",
    "Tomasz Jedruszek": "Morano44",
    "Tommy Arnold": "TommyArnoldArt",
    "Tony DiTerlizzi": "TonyDiTerlizzi",
    "Tyler Jacobson": "jacobsontyler",
    "Tyler Walpole": "TylerWalpole",
    "Uriah Voth": "Youriah90",
    "Vance Kovacs": "VanceKovacs",
    "Veronique Meignaud": "veloutier",
    "Victor Adame Minguez": "victoradameart",
    "Vincent Proce": "vproceart",
    "Wesley Burt": "wesburt",
    "Winona Nelson": "winonanelson",
    "Wylie Beckert": "wyliebeckert",
    "Yeong-Hao Han": "Thefooyee",
    "yigit koroglu": "yigitkoroglu",
    "Yongjae Choi": "indusconcept",
    "Zack Stella": "zack_stella",
    "Zezhou Chen": "ZezhouArt",
    "⚡️dani⚡️": "danipendergast",
    "ナブランジャ": "nablange",
    "中坪宏太(੭ ᐕ)੭": "kota_nakatsubo",
    "中塚理恵🌸Rien.": "kakihito2011",
    "前河 悠一": "YuichiMaekawa",
    "奥田まがね": "MaganeO",
    "山本章史/Yamamoto Akifumi": "yam248",
    "村山竜大": "ovopack",
    "田島幸枝 YukieTAJIMA @育児中": "YukieTAJIMA",
    "百瀬寿（ももせ ひさし）イラストレーター、ディレクター": "momos_page",
    "碧 風羽 Goods shop OPEN🐈 - Foo Midori": "foomidori",
    "篠丸峰山 (シノマル)": "shinomaru_hozan",
    "萩谷薫": "hagiya_k",
    "藤ちょこ@画集発売中": "fuzichoco",
    "風間雷太RaitaKazama": "kazamaraita",
    "黒葉.K": "__CloverK",
    "🌻✨🌈 Edge 🌈✨🌻": "ArtOfEdge",
    "🦄🔆KNIIO says BLM🎨": "kniiothedreamer",
    "🦌Julio Reyna🦇": "Hensy39",
}

def get_artist_handle(common_name: str) -> str:
    return f"@{ARTISTS[common_name]}" if common_name in ARTISTS else common_name